### ISSUE TITLE
failed should assertion does not fail test

### ISSUE THREAD

**Issue by chinenual** [StephenDavidson/electron-spectron-example#15]
@StephenDavidson  - thanks for putting this example project up on github.  I used an earlier version to bootstrap my test suite.

I'm in the process of updating to Electron 11.1.0, so have to update all my tests to Spectron 13 (and hence webdriverio v6).  Lots of changes.  I've noticed that "should" assertions aren't causing tests to be marked "failed".  For example, if I take your example and edit the following should, it still runs and "passes" the test!   Help?

```diff
diff --git a/test/search.js b/test/search.js
index fd17a68..a1d338f 100644
--- a/test/search.js
+++ b/test/search.js
@@ -32,7 +32,8 @@ describe('Sample Test', () => {
     const inputEl = await (app.client.$(searchPage.searchField))
     inputEl.setValue(input)
     inputEl.getValue()
-      .should.eventually.equal(input)
+      .should.eventually.equal('something wrong') //(input))
+
     const searchButton = await (app.client.$(searchPage.searchButton))
     searchButton.click()
     app.client.$(searchPage.searchResult)
```

**Comment by StephenDavidson** [comment]
Thanks for the report!

This is now resolved. It was due to me mixing async functions with chai as promised. I have removed chai as promised in the latest version to reflect this and it will now fail as expected.

**Comment by chinenual** [comment]
Thanks @StephenDavidson!  That solved my problem too.
